Adding Spanish Translation for the Pyladies Berlin Website
PyLadiesBerlin/PyLadiesBerlin.github.io pull request #88
Opened 2024-05-21 19:45 UTC by mjmolina

Hello!

**Goal of this PR:** Website translation to Spanish.

2024-05-21 20:32 UTC, sleepypioneer approved these changes
Muy Bien, Gracias! 🙌 🇪🇸

2024-05-23 20:50 UTC, cmaureir requested changes

2024-05-23 20:50 UTC, cmaureir commented on content/pages/es/about.rst
> +PyLadies es un grupo internacional de tutoría para géneros marginados, como personas no binarias, personas trans y mujeres en la tecnología, con el objetivo de ayudar a nuestra comunidad a convertirs
```suggestion
PyLadies es un grupo internacional de tutoría para géneros marginados, como personas no binarias, personas trans y mujeres en la tecnología, con el objetivo de ayudar a nuestra comunidad a convertirse en participantes activos y líderes en la comunidad de código abierto de Python. ¡Todos los niveles son bienvenidos!
```

2024-05-23 20:50 UTC, cmaureir commented on content/pages/es/about.rst
> +Creemos que el conocimiento es para todos. Al mismo tiempo, nuestros eventos tienen como objetivo principal empoderar a las mujeres y a las minorías de género en la comunidad tecnológica. Por ello, s
```suggestion
Creemos que el conocimiento es para todas las personas. Al mismo tiempo, nuestros eventos tienen como objetivo principal empoderar a las mujeres y a las minorías de género en la comunidad tecnológica. Por ello, si no te identificas como parte de ninguna de ellas, te pedimos que seas consciente de esta situación y hagas que tu presencia sea discreta, por ejemplo, viniendo con una mujer o una persona de una minoría de género para garantizar el equilibrio de género, y que consideres que no se te escucha más ni ocupas más espacio que los demás en los debates y secciones de preguntas.
```

2024-05-23 20:50 UTC, cmaureir commented on content/pages/es/about.rst
> +* Pregúntanos!
```suggestion
* ¡Pregúntanos!
```

2024-05-23 20:50 UTC, cmaureir commented on content/pages/es/jobs.rst
> +Echa un vistazo a nuestro `slack`_ en el canal #jobs-europe canal y #jobs (este último canal tiene sobre todo Estados Unidos puestos de trabajo)
```suggestion
Echa un vistazo a nuestro `slack`_ en el canal #jobs-europe canal y #jobs (este último canal tiene puestos de trabajo en Estados Unidos)
```

2024-05-23 20:50 UTC, cmaureir commented on content/pages/es/jobs.rst
> +  - Publica el trabajo directamente en nuestro `slack`_ en el canal #job-europe.
```suggestion
  - Publica el trabajo directamente en nuestro `slack`_ en el canal #jobs-europe.
```

2024-05-23 20:50 UTC, cmaureir commented on content/pages/es/meetups.rst
> +:summary: Meetups mensual de Pyladies Berlin
```suggestion
:summary: Meetups mensual de PyLadies Berlin
```

2024-05-23 20:50 UTC, cmaureir commented on content/pages/es/meetups.rst
> +empezar a programar con Python.
```suggestion
empezar a programar con Python más fácil.
```

2024-05-23 20:50 UTC, cmaureir commented on content/pages/es/meetups.rst
> +porque creemos que la vida (tecnológica) es mucho más que programar.
```suggestion
Tenemos diferentes niveles en los diferentes meetups, desde principiantes hasta expertos en temas específicos. A menudo comenzamos nuestros eventos con una charla de 10 minutos sobre un "superpoder sin programar" porque creemos que la vida (tecnológica) es mucho más que programar.
```

2024-05-23 20:55 UTC, cmaureir approved these changes

2024-05-23 20:55 UTC, merged

2024-05-23 20:55 UTC, cmaureir commented
¡Gracias!